# This file was generated by GoReleaser. DO NOT EDIT.
cask "superdocu" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "74ba0c5b3e06ebf48f80f155753b32ef1d1db3cf9e0115f580d10fd7a18055ab"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b13f74eab2ff4dac6a4b1698bc859f312824ca3e4cc91169784a6f5774b700a9"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5facf89d28adaffee19545d479f225275663d990031f316a8b480cbfb1a27aa4"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "337a08d8a1f8dbac6beb8a034e6716a2f59078793ff14fc0c7c9090aa572cb35"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "superdocu"
  desc "Superdocu API v2 command-line client"
  homepage "https://developers.superdocu.com/api-v2/tutorial"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "superdocu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/superdocu"]
    end
  end

  # No zap stanza required

end
