# This file was generated by GoReleaser. DO NOT EDIT.
cask "superdocu" do
  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "30ea7f98fe4ab76b645f5d4a5553a1e95077c4bd209641e0f22a82035c9cde12"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd9cdc5cc91de816a069de9ba0086bee33f185d4d4a7aaa996f086ef8c4dcef1"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9131cf8718c094356c3ad496267887b2741b0debaf6c008bc4a316d4181517b5"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "32871c0ee0d1e90c153411f02750488d9f999cdb52e44f9a6183628e7dabcd2b"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "superdocu"
  desc "Superdocu API v2 command-line client"
  homepage "https://developers.superdocu.com/api-v2/tutorial"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "superdocu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/superdocu"]
    end
  end

  # No zap stanza required
end
