# This file was generated by GoReleaser. DO NOT EDIT.
cask "superdocu" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "7fa0ca316232786154b17c8fd3362fc5e7f91efc86fa6db5956be837c6b21a5c"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9939bc43241c3628769a9c1184fa8d50ebb97311a7baf8bbc9dc1cd4fb2b1c6"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "11eeaa49b70a30cb6c45e2581e97370980edb2f799f3f89e3e4870a316b1c568"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "df005e058d06095d34c4a7992f83f1ac8ad105418b55b6a48166cf2e97e3ea0e"
      url "https://github.com/Superdocu/cli/releases/download/v#{version}/superdocu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "superdocu"
  desc "Superdocu API v2 command-line client"
  homepage "https://developers.superdocu.com/api-v2/tutorial"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "superdocu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/superdocu"]
    end
  end

  # No zap stanza required
end
